---
homebrew_packages:
  - wget
  - vim
  - fortune

gems:
  - i2cssh # OSX only


vim_conflict_files:
  - .vim/bundle/syntastic/syntax_checkers/puppet
  - .vim/bundle/syntastic/syntax_checkers/go
  - .vim/bundle/syntastic/syntax_checkers/coffee

pacman_packages:
  - zsh
  - git
  - gvim
  - cmake
  - wget
  - rsync
  - htop
  - networkmanager
  - sudo # required for pacaur
  - expac # required for pacaur
  - i3
  - networkmanager
  - "nm-applet"
  - dmenu
  # - pacaur # This is installed from the AUR; depends on AUR packages
