---
- copy: src={{ item }} dest=/root/.{{ item | basename }}  mode=644
  sudo: yes
  with_fileglob:
    - ./root/*

- file: path=/root/.vim  state=directory mode=755
- file: path=/root/.zsh  state=directory mode=755
- copy: dest=/root/.vim src=roles/dotfiles/files/default/vim/
- copy: dest=/root/.zsh src=roles/dotfiles/files/default/zsh/

